apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ullma1vbz-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ullma1vbz-nodejs 
  name: ullma1vbz-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: ullma1vbz-nodejs 
